college_finder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from sign_in import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', auth_views.login, name = 'login'),
    url(r'^logout/', auth_views.logout, name = 'logout'),
    url(r'^sign_in/', include(('sign_in.urls', 'sign_in'), namespace='sign_in')),
    url(r'^colleges/', include(('colleges.urls', 'colleges'), namespace='colleges')),
    url(r'^$', views.home, name = 'home'),
]

colleges/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
				url(r'^search/$', views.search, name = 'search'),
				url(r'^add/$', views.add_college, name = 'add'),]

sign_in/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
				url(r'^register/$', views.register, name = 'register'),
				url(r'^profile/$', views.profile, name = 'profile'),
				url(r'^update/$', views.update, name = 'update'),]

colleges/models.py
from django.db import models


class College(models.Model):
	name = models.CharField(max_length = 200)
	average_cost = models.IntegerField()
	location = models.CharField(max_length = 70)
	website = models.CharField(max_length = 1000)

	def __str__(self):
		return self.name

sign_in/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


class Profile(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	name = models.CharField(max_length = 100)
	gre = models.IntegerField(validators = [MinValueValidator(0), MaxValueValidator(340)])
	cgpa = models.FloatField(validators = [MinValueValidator(0), MaxValueValidator(10)])


	def __str__(self):
		return self.name

colleges/forms.py
from django import forms
from .models import College


class CollegeForm(forms.ModelForm):
	class Meta:
		model = College
		fields = ['name', 'average_cost', 'location', 'website']
		help_texts = {'average_cost': 'Enter the cost in lakhs'}

sign_in/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User


class RegistrationForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput())


	class Meta:
		model = User
		fields = ['username', 'password', 'email']
		help_texts = {'username': None, 'password': None, 'email': None}


	def clean_email(self):
		email = self.cleaned_data.get('email')
		username = self.cleaned_data.get('username')
		if email and User.objects.filter(email = email).exclude(username = username).exists():
			raise forms.ValidationError(u'Email Already Registered')
		return email


class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		exclude = ['user']

colleges/views.py
from django.shortcuts import render, redirect
import os
from os import listdir
from os.path import isfile, join
import pickle
from sign_in.models import Profile
from django.http import HttpResponse
from .models import College
from .forms import CollegeForm


def predictor(student):
	to_test = student
	settings_dir = os.path.dirname(__file__)
	PROJECT_ROOT = os.path.abspath(os.path.dirname(settings_dir))
	mypath = PROJECT_ROOT + '/colleges/ml/'
	all_files = [f for f in listdir(mypath) if isfile(join(mypath, f))]
	colleges = []

	for file in all_files:
		loaded_model = pickle.load(open(mypath + file, 'rb'))
		result = loaded_model.predict(to_test)

		if (int)(0.5 * result[0] + 0.5) >= 1:
			name = ''
			i = 0
			while file[i] != '.':
				name += file[i]
				i += 1
			colleges.append(name)
	return colleges


def checker(user):	
	profile = Profile.objects.get(user = user)
	possible_colleges = predictor([[profile.gre, profile.cgpa]])

	college_list = []

	for college in possible_colleges:
		college_details = College.objects.get(name = college)
		college_list.append(college_details)

	return college_list


def add_college(request):
	if request.user.is_authenticated and request.user.is_superuser:
		if request.method == "POST":
			college_form = CollegeForm(request.POST)

			if college_form.is_valid():
				college_form.save()
				return redirect('colleges:add')
		else:
			college_form = CollegeForm()
		return render(request, 'colleges/add.html', {'college_form': college_form})

def search(request):
	print('in search')

	if request.user.is_authenticated:
		user = request.user
		colleges = checker(user)
		colleges_copy = []
		colleges_copy1 = []

		maxCost = location = None
		
		maxCost = request.POST.get('maxRange')
		location = request.POST.get('location')
		print(maxCost, location)
		if maxCost is None and location is None:
			colleges_copy = colleges

		elif maxCost is not None and location is None:
			maxCost = (int)(maxCost)
			for college in colleges:
				if college.average_cost <= maxCost:
					colleges_copy.append(college)

		elif maxCost is None or maxCost is '' and location is not None:
			for college in colleges:
				if location.lower() in college.location.lower():
					colleges_copy.append(college)

		else:
			maxCost = (int)(maxCost)
			for college in colleges:
				if college.average_cost <= maxCost:
					colleges_copy1.append(college)

			for college in colleges_copy1:
				if location.lower() in college.location.lower():
					colleges_copy.append(college)

		return render(request, 'colleges/college_list.html', {'colleges_copy': colleges_copy})
	return redirect('login')

sign_in/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from .models import Profile
from django.http import HttpResponse
from .forms import ProfileForm, RegistrationForm
from django.contrib.auth.decorators import login_required

def home(request):
	if request.user.is_authenticated:
		return redirect('colleges:search')
	return redirect('login/')

def register(request):
	if request.method == "POST":

		user_form = RegistrationForm(request.POST)
		profile_form = ProfileForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()

			user.set_password(user.password)
			user.save()

			username = user_form.cleaned_data.get('username')
			raw_password = user_form.cleaned_data.get('password')

			profile = profile_form.save(commit = False)
			profile.user = user
			profile.save()

			login(request, authenticate(username = username, password = raw_password))
			return redirect('/')
	else:
		user_form = RegistrationForm()
		profile_form = ProfileForm()
	return render(request, 'sign_in/register.html', {'user_form': user_form, 'profile_form': profile_form})


def profile(request):
	if request.user.is_authenticated:
		user = request.user
		profile = Profile.objects.get(user = user)
		return render(request, 'sign_in/profile.html', {'profile': profile})
	return redirect('login/')


@login_required(login_url = 'login/')
def update(request):
	profile = Profile.objects.get(user = request.user)
	if request.method == 'POST':

		new_score = request.POST.get('score')
		new_cgpa = request.POST.get('cgpa')

		if (int)(new_score) > 340 or (int)(new_cgpa) > 10:
			return render(request, 'sign_in/update.html')

		profile.gre = new_score
		profile.cgpa = new_cgpa
		profile.save()
		return redirect('sign_in:profile')
	return render(request, 'sign_in/update.html')

colleges/templates/colleges/add.html
{% extends 'colleges/home.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ college_form.as_p }}
	<button type="submit">Add College</button>
</form>
{% endblock %}

colleges/templates/colleges/college_list.html
{% extends 'colleges/home.html' %}

{% block content %}
	<div class="row row-flex">
	{% for college in colleges_copy %}			
		<div class="content col-sm-12 col-md-12 col-lg-6">
			<div class="card mx-5 my-5">
			  	<div class="card-body">
				    <h5 class="card-title">{{ college.name }}</h5>
				    <br>
				    <h6 class="card-subtitle mb-2 text-muted">Location: {{ college.location }}</h6>				    
				    <p class="card-text">Average Cost: {{ college.average_cost }} lakhs (2 years)</p>
				    <br>
			    	<a target="blank" href="{{ college.website }}" class="card-link">College Website</a>
			  	</div>
			</div>
		</div>
	{% endfor %}															
	</div> 
{% endblock %}

colleges/templates/colleges/home.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  	<head>
  		<title>College Finder</title>

	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster|Raleway">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.0/font/css/open-iconic-bootstrap.css">
	    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	    <script type="text/javascript" src="{% static 'js/home.js' %}"></script>	

  	</head>
  	<body>  
		<section class="parallax">
			<h2>Welcome to College Finder</h2>
			<br><br>
			<a href="#toggle" class="btn-get-started">Get Started</a>
		</section>
		<br>
		<!-- Main -->
		<div class="wrapper" >
		    <!-- Sidebar -->
		    <nav id="sidebar" style="border:1px solid #FF5733; background-color:#FF5733;">
		        <div class="sidebar-header">
		            <h4>Hello <a href="{% url 'sign_in:profile' %}">{{ request.user.username }}</a></h4>
		        </div>
		        <ul class="list-unstyled components" >
		            <li>
		            	<a href="{% url 'sign_in:update' %}">Update Profile</a>
		            </li>
		            <br>
		            <li>
		            	<a href="{% url 'logout' %}">Logout</a>
		            </li>		            
		            <br><br>	          
		            <p>Filter By:</p>
		            <li>
		                <span>Budget (In lakhs)</span>	      
			            <form method="post" action="{% url 'colleges:search' %}">
			            	{% csrf_token %}
			            	<li><input id="end" type="text" name="maxRange" placeholder="End"></li><br>
			            	<span>Location</span>	 
			            	<li><input id="loc" type="text" name="location" placeholder="location"></li><br>
			            	<li><button class="btn btn-primary">Search</button></li>
			            </form>
		            </li>
		            
		            
		            <br><br>
		        </ul>
		    </nav>
		    <div id="content">
<!-- 		    <center> -->
			    <nav class="navbar navbar-expand-lg navbar-light bg-light">
			        <div class="container-fluid">
			            <button type="button" id="sidebarCollapse" class="btn btn-info">
			                <i class="fas fa-align-left"></i>
			                <span id="toggle">Toggle Sidebar</span>
			            </button>		            
			        </div>				        		    
			    </nav>
			    <br><br>	
			    <div class="position">		
			    	{% block content %}
			    	{% endblock %}
				</div>					  
			</div>
		</div>
		<br><br><br>
  	</body>
</html>	   			

sign_in/templates/sign_in/base.html
<!doctype html>
<html lang="en">
  	<head>
  		<title>College Finder</title>

  		{% load staticfiles %}
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.0/font/css/open-iconic-bootstrap.css">
	    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>	

  	</head>
  	<body>    	
		<div class="container">
			<div class="login-form">
				<div class="main-div">
	    			<div class="panel">
	   					<h2>College Finder</h2>
	   					<br><br>
	   				</div>
	   				{% block content %}
	   				{% endblock content %}
	    		</div>
			</div>
		</div>
  	</body>
</html>	   				

sign_in/templates/sign_in/profile.html
{% extends 'colleges/home.html' %}

{% block content %}
<div style="padding-left: 30px;">
	<h1>Name : {{ profile.name }}</h1><br>
	<h4>GRE Score : {{ profile.gre }}</h4><br>
	<h4>CGPA : {{ profile.cgpa }}</h4><br>
</div>
{% endblock %}

sign_in/templates/sign_in/register.html
{% extends "sign_in/base.html" %}

{% block content %}
<form method="post" id="register">
	<div style="display: table;">
	{% csrf_token %}
	<div class="back">
		<a href="/login/"><span class="oi oi-arrow-circle-left"></span> Back</a>
	</div>
	<br>	    

	{% for field in user_form %}
		<div class="form-group" style="display: table-row;">
<!-- 			<div>
				<span class="text-danger la">{{ field.errors }}</span>
			</div>  -->
			<span>{{ field.label_tag }}</span>
			<span>{{ field }}</span>
		</div>
		<br>
	{% endfor %}
	{% for field in profile_form %}
		<div class="form-group" style="display: table-row;">
<!-- 			<div>
				<span class="text-danger la">{{ field.errors }}</span>
			</div>  -->
			<span>{{ field.label_tag }}</span>
			<span>{{ field }}</span>
		</div>
		<br>
	{% endfor %}

<!-- 	<div class="form-group">
		<input type="text" class="form-control" id="name" placeholder="Name">
	</div>
	<div class="form-group">
		<input type="email" class="form-control" id="email" placeholder="Email-ID">
	</div>
	<div class="form-group">
		<input type="text" class="form-control" id="username" placeholder="Username">
	</div>
	<div class="form-group"> 		       	
		<input type="password" class="form-control" id="password" placeholder="Password">
	</div>	
	<div class="form-group">
		<input type="number" class="form-control" id="gre" placeholder="GRE Score">
	</div>	
	<div class="form-group">
		<input type="number" class="form-control" id="inputToefl" placeholder="TOEFL Score">
	</div>	
	<div class="form-group">
		<input type="number" class="form-control" id="cgpa" placeholder="Enter CGPA">
	</div> -->	
	</div>		        		        	       			        				        		
	<br><br>		        
	<button type="submit" class="btn btn-primary">Register</button>
	<br><br>	   
</form>
{% endblock %}

sign_in/templates/sign_in/update.html
{% extends 'colleges/home.html' %}

{% block content %}
<div style="margin-left: 40px;">
<form method="post" id="update">
	{% csrf_token %}
	<label>New GRE Score: </label>
	<input type="text" name="score" width="20">
	<br><br><br>
	<label>New CGPA: </label>
	<input type="text" name="cgpa" width="20">
	<br><br><br>
	<button type="submit" class="btn btn-success">Submit</button>
</form>
</div>
{% endblock %}